GET http://localhost:3000/subscribers
###

GET http://localhost:3000/subscribers/61ec680a1ebafcdc21b6bcbb
###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name":"test man3",
    "subscribedToChannel":"A server3 ? "
}
###



DELETE http://localhost:3000/subscribers/61ec6de542ecd15a8064e5c9
###



PATCH http://localhost:3000/subscribers/61ec7b4050e8812d0ea1c3ce
Content-Type: application/json

{
    "name":"test man2pog"
}
